---
- name: Mac OSX Workstation Configuration
  hosts: bextop
  vars_files:
    - varfiles/global_vars.yml
    - varfiles/mac_vars.yml
  tasks:
    - import_tasks: tasks/homebrew-pkginstall.yml
      when: not ansible_check_mode
    - import_tasks: tasks/ssh-gpg-dotfiles.yml
    - import_tasks: tasks/mac-dotfiles.yml
    - import_tasks: tasks/vim-setup.yml
