---

- name: Linux Workstation Configuration
  hosts: bexsrv
  vars_files:
    - varfiles/linux_vars.yml
  tasks:
    - import_tasks: tasks/host.yml
    - import_tasks: tasks/pkguninstall.yml
    - import_tasks: tasks/pkgupdate.yml
    - import_tasks: tasks/pkginstall-server.yml
    - import_tasks: tasks/vim-setup.yml
    - import_tasks: tasks/dotfiles-server.yml
    - import_tasks: tasks/gnome-dirs.yml
    - import_tasks: tasks/gnome-settings.yml
    - import_tasks: tasks/services-server.yml
