---
- name: Linux Workstation Configuration
  hosts: bexsrv
  vars_files:
    - varfiles/global_vars.yml
    - varfiles/server_vars.yml
  tasks:
    - import_tasks: tasks/host.yml
      when: not ansible_check_mode
    - import_tasks: tasks/server-packages.yml
      when: not ansible_check_mode
    - import_tasks: tasks/server-package-config.yml
    - import_tasks: tasks/tailscale-configuration.yml
    - import_tasks: tasks/vim-setup.yml
    - import_tasks: tasks/server-dotfiles.yml
    - import_tasks: tasks/server-services.yml
      when: not ansible_check_mode
    - import_tasks: tasks/server-user.yml
      when: not ansible_check_mode
    - import_tasks: tasks/container-unifi.yml
      when: not ansible_check_mode
    - import_tasks: tasks/blacklist-i2c_piix4.yml
# Temporary fix
    - import_tasks: tasks/irqbalance.service-override.yml
