---
# User level Configs

- name: Create ~/bin directory
  file:
    path: "~/bin/"
    state: directory
    mode: 0700

- name: Install ~/bin files
  shell: "stow -d {{ playbook_dir }}/dot-files -t ~/bin/ bin"

- name: Install ~/bin - linux specific files
  shell: "stow -d {{ playbook_dir }}/dot-files -t ~/bin/ bin-linux"
  when: ansible_facts['distribution'] != "MacOSX"

- name: Install ~/bin - mac specific files
  shell: "stow -d {{ playbook_dir }}/dot-files -t ~/bin/ bin-mac"
  when: ansible_facts['distribution'] == "MacOSX"

