---
- name: Install git configuration files
  shell: "stow -d {{ playbook_dir }}/dot-files -t ~/ git"

- name: Remove temporary ~/.ssh
  file:
    path: ~/.ssh
    state: absent

- name: Install ssh dotfiles
  file:
    src: "{{ playbook_dir }}/dot-files/secure/ssh"
    dest: "~/.ssh"
    state: link

- name: Remove temporary ~/.gnupg/gpg-agent.conf
  file:
    path: ~/.gnupg/gpg-agent.conf
    state: absent

- name: Remove temporary ~/.gnupg/sshcontrol
  file:
    path: ~/.gnupg/sshcontrol
    state: absent

- name: Install ~/.gnupg dotfiles
  shell: "stow -d {{ playbook_dir }}/dot-files -t ~/.gnupg gnupg"

- name: Remove Linux ~/.gnupg/gpg-agent.conf on MacOSX
  file:
    path: ~/.gnupg/gpg-agent.conf
    state: absent
  when: ansible_facts['distribution'] == "MacOSX"

- name: Link the correct gpg-agent.conf on MacOSX
  file:
    src: "{{ playbook_dir }}/dot-files/gnupg/gpg-agent.conf.macosx"
    dest: "~/.gnupg/gpg-agent.conf"
    state: link
  when: ansible_facts['distribution'] == "MacOSX"
