---
- name: Remove ~/Videos
  file:
    path: ~/Videos
    state: absent

- name: Remove ~/Pictures
  file:
    path: ~/Pictures
    state: absent

- name: Remove ~/Public
  file:
    path: ~/Public
    state: absent

- name: Remove ~/Music
  file:
    path: ~/Music
    state: absent

- name: Remove ~/Templates
  file:
    path: ~/Templates
    state: absent

- name: Remove ~/Desktop
  file:
    path: ~/Desktop
    state: absent

- name: Remove ~/.config/user-dirs.dirs
  file:
    path: ~/.config/user-dirs.dirs
    state: absent

- name: Install xdg-dirs configuration files - this permanently gets rid of the default dirs I don't use
  shell: "stow -d {{ playbook_dir }}/dot-files -t ~/.config xdg-users-dirs && /usr/bin/xdg-user-dirs-update"
