---
- name: Install git configuration files
  copy:
    src: "{{ playbook_dir }}/dot-files/git/gitconfig"
    dest: ~/.gitconfig
    owner: "{{ myuser }}"
    group: "{{ mygroup }}"
    mode: 0644
    backup: yes

- name: Install zshrc
  copy:
    src: "{{ playbook_dir }}/dot-files/zsh-mac/zshrc"
    dest: ~/.zshrc
    owner: "{{ myuser }}"
    group: "{{ mygroup }}"
    mode: 0644
    backup: yes
