# Add repo for virtualbox

- name: "Add VirtualBox Repo"
  become: yes
  yum_repository:
    name="virtualbox"
    description="Fedora $releasever - $basearch - VirtualBox"
    baseurl="http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch"
    gpgkey="https://www.virtualbox.org/download/oracle_vbox.asc"
    enabled=1
    gpgcheck=1
    repo_gpgcheck=1

- name: Package install - VirtualBox
  become: yes
  dnf:
    state: present
    name: VirtualBox-{{ virtualbox_version }}
  notify:
    - rebuild-vbox-kernel

- name: Package install - Dependencies for VirtualBox Module Build
  become: yes
  dnf:
    state: present
    name: 
      - binutils
      - gcc
      - make
      - patch
      - libgomp
      - glibc-headers
      - glibc-devel
      - kernel-headers
      - kernel-devel
      - dkms

- name: Add {{ myuser }} to the vboxusers group
  user:
    name: {{ myuser }}
    groups: vboxusers
    append: yes
