---
# Modified from: https://gist.github.com/mrlesmithjr/f3c15fdd53020a71f55c2032b8be2eda

- name: Updating Homebrew
  become: false
  homebrew:
    update_homebrew: true

- name: Upgrading Homebrew Packages
  become: false
  homebrew:
    upgrade_all: true
  register: result
  until: result is successful

- name: Installing Homebrew Cask Packages
  become: false
  vars:
    brew_cask_packages:
      - osxfuse
      - vlc
      - libreoffice
      - chromium
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: present
  register: result
  until: result is successful

- name: Installing Homebrew Packages
  become: false
  vars:
    brew_packages:
      - pinentry-mac
      - gpg
      - pass
      - pass-otp
      - gocryptfs
      - stow
      - terminal-notifier
      - python3
      - imapsync
      - zbar
      - youtube-dl
      - restic
      - rclone
      - bat
      - exa
      - ripgrep-all
      - sshuttle
      - ledger
  homebrew:
    name: "{{ brew_packages }}"
    state: present
  register: result
  until: result is successful
