---
- name: rpm-ostreed-upgrade-reboot - install service
  become: yes
  template:
    src: "{{ playbook_dir }}/dot-files/systemd-system/rpm-ostreed-upgrade-reboot.service"
    dest: /etc/systemd/system/rpm-ostreed-upgrade-reboot.service
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: install rpm-ostreed-upgrade-reboot.timer should run on Sundays at 3am
  become: yes
  copy:
    src: "{{ playbook_dir }}/dot-files/systemd-system/rpm-ostreed-upgrade-reboot.timer"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: enable rpm-ostreed-upgrade-reboot.timer
  become: yes
  systemd:
    name: rpm-ostreed-upgrade-reboot.timer
    enabled: yes
    state: started