---
- name: Create ~/.ssh
  file:
    path: ~/.ssh
    state: directory

- name: ssh config file
  copy:
    src: "{{ playbook_dir }}/dot-files/ssh/config"
    dest: ~/.ssh/
    owner: "{{ myuser }}"
    group: "{{ mygroup }}"
    mode: 0644
    backup: yes

- name: Install current public keys - delete when moving off of GPG
  copy:
    src: "{{ item }}"
    dest: ~/.ssh/
    owner: "{{ myuser }}"
    group: "{{ mygroup }}"
    mode: 0600
    backup: yes
  with_fileglob:
    - "{{ playbook_dir }}/dot-files/ssh/*.pub"

- name: Install a key I don't think is even used :(
  copy:
    src: "{{ playbook_dir }}/dot-files/ssh/google_compute_engine"
    dest: ~/.ssh/
    owner: "{{ myuser }}"
    group: "{{ mygroup }}"
    mode: 0600
    backup: yes

# Can the below be deleted?

- name: Remove temporary ~/.gnupg/gpg-agent.conf
  file:
    path: ~/.gnupg/gpg-agent.conf
    state: absent

- name: Remove temporary ~/.gnupg/sshcontrol
  file:
    path: ~/.gnupg/sshcontrol
    state: absent

- name: Install ~/.gnupg dotfiles
  shell: "stow -d {{ playbook_dir }}/dot-files -t ~/.gnupg gnupg"

- name: Remove Linux ~/.gnupg/gpg-agent.conf on MacOSX
  file:
    path: ~/.gnupg/gpg-agent.conf
    state: absent
  when: ansible_facts['distribution'] == "MacOSX"

- name: Link the correct gpg-agent.conf on MacOSX
  file:
    src: "{{ playbook_dir }}/dot-files/gnupg/gpg-agent.conf.macosx"
    dest: "~/.gnupg/gpg-agent.conf"
    state: link
  when: ansible_facts['distribution'] == "MacOSX"
