---
- name: Set iptables to legacy in alternatives to help with tailscale end point
  become: yes
  shell: "alternatives --set iptables /usr/sbin/iptables-legacy"
  when: ansible_hostname != 'vpn'

- name: Set firewalld to use iptables-legacy to help with tailscale end point
  become: yes
  lineinfile:
    path: /etc/firewalld/firewalld.conf
    regexp: '^FirewallBackend='
    line: 'FirewallBackend=iptables'

- name: IPv4 forwarding
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv4.ip_forward = 1'

- name: IPv6 forwarding
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    line: 'net.ipv6.conf.all.forwarding = 1'

- name: enable tailscale - it needs to be started manually for first log in
  become: yes
  systemd:
    name: tailscaled.service
    enabled: yes